## IMPORTS
import os
import sys

# RNA
import RNA


"""
bla.fa:
>BlaBla
TTTTTTCTTTATAATTATTCCCCTATTTGAAAAATCAACTTGTATATGAGGCAGCAAACACCTTGCAGAGCAGCATTCCCTTTTAGTTTCAGGACGTGGTGGTGGATGGAACCACTGTAACCTGGCCTCCCTCCATGAGAGGAGGGAATCCAGGTGGCCATGTTGAAATGTGCCTGTGTGCAGCAAGGCTTCTGAAATGACAAGAGAGCCCAGCAGCTTCCAAAGCAGCTGTGACTCTGGATCTCACCCATCATCTCTGCTTCTCACTGTTAGAGGAGTGAATCTGTGCTGCCTTAGGAGGCATGGAACCTGGGACTTTTCTTCCTTGTTTAATGTTTAATTTTATTAAAATAATTTGTAAGTGATAGATGTTGATCTCGTGACAAAAGAGAGATTCCCTCTTTATAAAACTATTCTAACTAAAGATCTTTTGTAAGCCCATGTGTTAGAAATAAAACTTGAATATCCCC

CMD CALL:
RNAplfold -L 100 -W 100 -u 7 --commands foo.txt < bla.fa


Groesste Diff bei pos 299 mit > 0.01
"""

seq = "TTTTTTCTTTATAATTATTCCCCTATTTGAAAAATCAACTTGTATATGAGGCAGCAAACACCTTGCAGAGCAGCATTCCCTTTTAGTTTCAGGACGTGGTGGTGGATGGAACCACTGTAACCTGGCCTCCCTCCATGAGAGGAGGGAATCCAGGTGGCCATGTTGAAATGTGCCTGTGTGCAGCAAGGCTTCTGAAATGACAAGAGAGCCCAGCAGCTTCCAAAGCAGCTGTGACTCTGGATCTCACCCATCATCTCTGCTTCTCACTGTTAGAGGAGTGAATCTGTGCTGCCTTAGGAGGCATGGAACCTGGGACTTTTCTTCCTTGTTTAATGTTTAATTTTATTAAAATAATTTGTAAGTGATAGATGTTGATCTCGTGACAAAAGAGAGATTCCCTCTTTATAAAACTATTCTAACTAAAGATCTTTTGTAAGCCCATGTGTTAGAAATAAAACTTGAATATCCCC"


def run_api_cli_test():

    res = test_api(seq, 7, 100, 100)
    print(res)


def test_api(seq, region, window, span):

    ### Test with cutout after fold
    data = {'up': []}

    md = RNA.md()
    md.max_bp_span = span
    md.window_size = window
    # create new fold_compound object
    fc = RNA.fold_compound(str(seq), md, RNA.OPTION_WINDOW)
    # call prop window calculation
    fc.probs_window(region, RNA.PROBS_WINDOW_UP, up_callback, data)
    return data


def up_callback(v, v_size, i, maxsize, what, data):

    if what:
        data['up'].extend([v])


if __name__ == "__main__":
    run_api_cli_test()
